///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String jsonKeyMovieListCount = "count";
const String jsonKeyMovieListStart = "start";
const String jsonKeyMovieListTotal = "total";
const String jsonKeyMovieListSubjects = "subjects";
const String jsonKeyMovieListTitle = "title";
const String jsonKeyMovieListSubjectsRating = "rating";
const String jsonKeyMovieListSubjectsGenres = "genres";
const String jsonKeyMovieListSubjectsTitle = "title";
const String jsonKeyMovieListSubjectsCasts = "casts";
const String jsonKeyMovieListSubjectsDurations = "durations";
const String jsonKeyMovieListSubjectsCollect_count = "collect_count";
const String jsonKeyMovieListSubjectsMainland_pubdate = "mainland_pubdate";
const String jsonKeyMovieListSubjectsHas_video = "has_video";
const String jsonKeyMovieListSubjectsOriginal_title = "original_title";
const String jsonKeyMovieListSubjectsSubtype = "subtype";
const String jsonKeyMovieListSubjectsDirectors = "directors";
const String jsonKeyMovieListSubjectsPubdates = "pubdates";
const String jsonKeyMovieListSubjectsYear = "year";
const String jsonKeyMovieListSubjectsImages = "images";
const String jsonKeyMovieListSubjectsAlt = "alt";
const String jsonKeyMovieListSubjectsId = "id";
const String jsonKeyMovieListSubjectsImagesSmall = "small";
const String jsonKeyMovieListSubjectsImagesLarge = "large";
const String jsonKeyMovieListSubjectsImagesMedium = "medium";
class MovieListSubjectsImages {
/*
 {
  "small": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
  "large": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
  "medium": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp"
} 
*/

  String small;
  String large;
  String medium;

  MovieListSubjectsImages({
    this.small,
    this.large,
    this.medium,
  });
  MovieListSubjectsImages.fromJson(Map<String, dynamic> json) {
    small = json[jsonKeyMovieListSubjectsImagesSmall];
    large = json[jsonKeyMovieListSubjectsImagesLarge];
    medium = json[jsonKeyMovieListSubjectsImagesMedium];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyMovieListSubjectsImagesSmall] = small;
    data[jsonKeyMovieListSubjectsImagesLarge] = large;
    data[jsonKeyMovieListSubjectsImagesMedium] = medium;
    return data;
  }
}

const String jsonKeyMovieListSubjectsDirectorsAvatars = "avatars";
const String jsonKeyMovieListSubjectsDirectorsName_en = "name_en";
const String jsonKeyMovieListSubjectsDirectorsName = "name";
const String jsonKeyMovieListSubjectsDirectorsAlt = "alt";
const String jsonKeyMovieListSubjectsDirectorsId = "id";
const String jsonKeyMovieListSubjectsDirectorsAvatarsSmall = "small";
const String jsonKeyMovieListSubjectsDirectorsAvatarsLarge = "large";
const String jsonKeyMovieListSubjectsDirectorsAvatarsMedium = "medium";
class MovieListSubjectsDirectorsAvatars {
/*
 {
  "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
  "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
  "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp"
} 
*/

  String small;
  String large;
  String medium;

  MovieListSubjectsDirectorsAvatars({
    this.small,
    this.large,
    this.medium,
  });
  MovieListSubjectsDirectorsAvatars.fromJson(Map<String, dynamic> json) {
    small = json[jsonKeyMovieListSubjectsDirectorsAvatarsSmall];
    large = json[jsonKeyMovieListSubjectsDirectorsAvatarsLarge];
    medium = json[jsonKeyMovieListSubjectsDirectorsAvatarsMedium];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyMovieListSubjectsDirectorsAvatarsSmall] = small;
    data[jsonKeyMovieListSubjectsDirectorsAvatarsLarge] = large;
    data[jsonKeyMovieListSubjectsDirectorsAvatarsMedium] = medium;
    return data;
  }
}

class MovieListSubjectsDirectors {
/*
 {
  "avatars": {
    "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
    "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
    "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp"
  },
  "name_en": "Yu Yang",
  "name": "饺子",
  "alt": "https://movie.douban.com/celebrity/1328441/",
  "id": "1328441"
} 
*/

  MovieListSubjectsDirectorsAvatars avatars;  String name_en;
  String name;
  String alt;
  String id;

  MovieListSubjectsDirectors({
    this.avatars,
    this.name_en,
    this.name,
    this.alt,
    this.id,
  });
  MovieListSubjectsDirectors.fromJson(Map<String, dynamic> json) {
    avatars = json[jsonKeyMovieListSubjectsDirectorsAvatars] != null ? MovieListSubjectsDirectorsAvatars.fromJson(json[jsonKeyMovieListSubjectsDirectorsAvatars]) : null;
    name_en = json[jsonKeyMovieListSubjectsDirectorsName_en];
    name = json[jsonKeyMovieListSubjectsDirectorsName];
    alt = json[jsonKeyMovieListSubjectsDirectorsAlt];
    id = json[jsonKeyMovieListSubjectsDirectorsId];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (avatars != null) {
      data['avatars'] = avatars.toJson();
    }
    data[jsonKeyMovieListSubjectsDirectorsName_en] = name_en;
    data[jsonKeyMovieListSubjectsDirectorsName] = name;
    data[jsonKeyMovieListSubjectsDirectorsAlt] = alt;
    data[jsonKeyMovieListSubjectsDirectorsId] = id;
    return data;
  }
}

const String jsonKeyMovieListSubjectsCastsAvatars = "avatars";
const String jsonKeyMovieListSubjectsCastsName_en = "name_en";
const String jsonKeyMovieListSubjectsCastsName = "name";
const String jsonKeyMovieListSubjectsCastsAlt = "alt";
const String jsonKeyMovieListSubjectsCastsId = "id";
const String jsonKeyMovieListSubjectsCastsAvatarsSmall = "small";
const String jsonKeyMovieListSubjectsCastsAvatarsLarge = "large";
const String jsonKeyMovieListSubjectsCastsAvatarsMedium = "medium";
class MovieListSubjectsCastsAvatars {
/*
 {
  "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
  "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
  "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp"
} 
*/

  String small;
  String large;
  String medium;

  MovieListSubjectsCastsAvatars({
    this.small,
    this.large,
    this.medium,
  });
  MovieListSubjectsCastsAvatars.fromJson(Map<String, dynamic> json) {
    small = json[jsonKeyMovieListSubjectsCastsAvatarsSmall];
    large = json[jsonKeyMovieListSubjectsCastsAvatarsLarge];
    medium = json[jsonKeyMovieListSubjectsCastsAvatarsMedium];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyMovieListSubjectsCastsAvatarsSmall] = small;
    data[jsonKeyMovieListSubjectsCastsAvatarsLarge] = large;
    data[jsonKeyMovieListSubjectsCastsAvatarsMedium] = medium;
    return data;
  }
}

class MovieListSubjectsCasts {
/*
 {
  "avatars": {
    "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
    "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
    "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp"
  },
  "name_en": "Yanting Lü",
  "name": "吕艳婷",
  "alt": "https://movie.douban.com/celebrity/1419996/",
  "id": "1419996"
} 
*/

  MovieListSubjectsCastsAvatars avatars;  String name_en;
  String name;
  String alt;
  String id;

  MovieListSubjectsCasts({
    this.avatars,
    this.name_en,
    this.name,
    this.alt,
    this.id,
  });
  MovieListSubjectsCasts.fromJson(Map<String, dynamic> json) {
    avatars = json[jsonKeyMovieListSubjectsCastsAvatars] != null ? MovieListSubjectsCastsAvatars.fromJson(json[jsonKeyMovieListSubjectsCastsAvatars]) : null;
    name_en = json[jsonKeyMovieListSubjectsCastsName_en];
    name = json[jsonKeyMovieListSubjectsCastsName];
    alt = json[jsonKeyMovieListSubjectsCastsAlt];
    id = json[jsonKeyMovieListSubjectsCastsId];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (avatars != null) {
      data['avatars'] = avatars.toJson();
    }
    data[jsonKeyMovieListSubjectsCastsName_en] = name_en;
    data[jsonKeyMovieListSubjectsCastsName] = name;
    data[jsonKeyMovieListSubjectsCastsAlt] = alt;
    data[jsonKeyMovieListSubjectsCastsId] = id;
    return data;
  }
}

const String jsonKeyMovieListSubjectsRatingMax = "max";
const String jsonKeyMovieListSubjectsRatingAverage = "average";
const String jsonKeyMovieListSubjectsRatingDetails = "details";
const String jsonKeyMovieListSubjectsRatingStars = "stars";
const String jsonKeyMovieListSubjectsRatingMin = "min";
const String jsonKeyMovieListSubjectsRatingDetails1 = "1";
const String jsonKeyMovieListSubjectsRatingDetails2 = "2";
const String jsonKeyMovieListSubjectsRatingDetails3 = "3";
const String jsonKeyMovieListSubjectsRatingDetails4 = "4";
const String jsonKeyMovieListSubjectsRatingDetails5 = "5";

class MovieListSubjectsRating {
/*
 {
  "max": 10,
  "average": 8.6,
  "details": {
    "1": 384,
    "2": 1292,
    "3": 10092,
    "4": 30482,
    "5": 35759
  },
  "stars": "45",
  "min": 0
} 
*/

  int max;
  double average;
  String stars;
  int min;

  MovieListSubjectsRating({
    this.max,
    this.average,
    this.stars,
    this.min,
  });
  MovieListSubjectsRating.fromJson(Map<String, dynamic> json) {
    max = json[jsonKeyMovieListSubjectsRatingMax];
    average = json[jsonKeyMovieListSubjectsRatingAverage].toDouble();
    stars = json[jsonKeyMovieListSubjectsRatingStars];
    min = json[jsonKeyMovieListSubjectsRatingMin];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyMovieListSubjectsRatingMax] = max;
    data[jsonKeyMovieListSubjectsRatingAverage] = average;
    data[jsonKeyMovieListSubjectsRatingStars] = stars;
    data[jsonKeyMovieListSubjectsRatingMin] = min;
    return data;
  }
}

class MovieListSubjects {
/*
 {
  "rating": {
    "max": 10,
    "average": 8.6,
    "details": {
      "1": 384,
      "2": 1292,
      "3": 10092,
      "4": 30482,
      "5": 35759
    },
    "stars": "45",
    "min": 0
  },
  "genres": [
    "剧情"
  ],
  "title": "哪吒之魔童降世",
  "casts": [
    {
      "avatars": {
        "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
        "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
        "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp"
      },
      "name_en": "Yanting Lü",
      "name": "吕艳婷",
      "alt": "https://movie.douban.com/celebrity/1419996/",
      "id": "1419996"
    }
  ],
  "durations": [
    "110分钟"
  ],
  "collect_count": 757191,
  "mainland_pubdate": "2019-07-26",
  "has_video": false,
  "original_title": "哪吒之魔童降世",
  "subtype": "movie",
  "directors": [
    {
      "avatars": {
        "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
        "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
        "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp"
      },
      "name_en": "Yu Yang",
      "name": "饺子",
      "alt": "https://movie.douban.com/celebrity/1328441/",
      "id": "1328441"
    }
  ],
  "pubdates": [
    "2019-07-13(大规模点映)"
  ],
  "year": "2019",
  "images": {
    "small": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
    "large": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
    "medium": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp"
  },
  "alt": "https://movie.douban.com/subject/26794435/",
  "id": "26794435"
} 
*/

  MovieListSubjectsRating rating;  List<String> genres;
  String title;
  List<MovieListSubjectsCasts> casts;
  List<String> durations;
  int collect_count;
  String mainland_pubdate;
  bool has_video;
  String original_title;
  String subtype;
  List<MovieListSubjectsDirectors> directors;
  List<String> pubdates;
  String year;
  MovieListSubjectsImages images;  String alt;
  String id;

  MovieListSubjects({
    this.rating,
    this.genres,
    this.title,
    this.casts,
    this.durations,
    this.collect_count,
    this.mainland_pubdate,
    this.has_video,
    this.original_title,
    this.subtype,
    this.directors,
    this.pubdates,
    this.year,
    this.images,
    this.alt,
    this.id,
  });
  MovieListSubjects.fromJson(Map<String, dynamic> json) {
    rating = json[jsonKeyMovieListSubjectsRating] != null ? MovieListSubjectsRating.fromJson(json[jsonKeyMovieListSubjectsRating]) : null;
  if (json[jsonKeyMovieListSubjectsGenres] != null) {
  var v = json[jsonKeyMovieListSubjectsGenres];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v);
  });
    genres = arr0;
    }
    title = json[jsonKeyMovieListSubjectsTitle];
  if (json[jsonKeyMovieListSubjectsCasts] != null) {
  var v = json[jsonKeyMovieListSubjectsCasts];
  var arr0 = List<MovieListSubjectsCasts>();
  v.forEach((v) {
  arr0.add(MovieListSubjectsCasts.fromJson(v));
  });
    casts = arr0;
    }
  if (json[jsonKeyMovieListSubjectsDurations] != null) {
  var v = json[jsonKeyMovieListSubjectsDurations];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v);
  });
    durations = arr0;
    }
    collect_count = json[jsonKeyMovieListSubjectsCollect_count];
    mainland_pubdate = json[jsonKeyMovieListSubjectsMainland_pubdate];
    has_video = json[jsonKeyMovieListSubjectsHas_video];
    original_title = json[jsonKeyMovieListSubjectsOriginal_title];
    subtype = json[jsonKeyMovieListSubjectsSubtype];
  if (json[jsonKeyMovieListSubjectsDirectors] != null) {
  var v = json[jsonKeyMovieListSubjectsDirectors];
  var arr0 = List<MovieListSubjectsDirectors>();
  v.forEach((v) {
  arr0.add(MovieListSubjectsDirectors.fromJson(v));
  });
    directors = arr0;
    }
  if (json[jsonKeyMovieListSubjectsPubdates] != null) {
  var v = json[jsonKeyMovieListSubjectsPubdates];
  var arr0 = List<String>();
  v.forEach((v) {
  arr0.add(v);
  });
    pubdates = arr0;
    }
    year = json[jsonKeyMovieListSubjectsYear];
    images = json[jsonKeyMovieListSubjectsImages] != null ? MovieListSubjectsImages.fromJson(json[jsonKeyMovieListSubjectsImages]) : null;
    alt = json[jsonKeyMovieListSubjectsAlt];
    id = json[jsonKeyMovieListSubjectsId];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (rating != null) {
      data['rating'] = rating.toJson();
    }
    if (genres != null) {
      var v = genres;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data[jsonKeyMovieListSubjectsGenres] = arr0;
    }
    data[jsonKeyMovieListSubjectsTitle] = title;
    if (casts != null) {
      var v = casts;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data[jsonKeyMovieListSubjectsCasts] = arr0;
    }
    if (durations != null) {
      var v = durations;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data[jsonKeyMovieListSubjectsDurations] = arr0;
    }
    data[jsonKeyMovieListSubjectsCollect_count] = collect_count;
    data[jsonKeyMovieListSubjectsMainland_pubdate] = mainland_pubdate;
    data[jsonKeyMovieListSubjectsHas_video] = has_video;
    data[jsonKeyMovieListSubjectsOriginal_title] = original_title;
    data[jsonKeyMovieListSubjectsSubtype] = subtype;
    if (directors != null) {
      var v = directors;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data[jsonKeyMovieListSubjectsDirectors] = arr0;
    }
    if (pubdates != null) {
      var v = pubdates;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v);
  });
      data[jsonKeyMovieListSubjectsPubdates] = arr0;
    }
    data[jsonKeyMovieListSubjectsYear] = year;
    if (images != null) {
      data['images'] = images.toJson();
    }
    data[jsonKeyMovieListSubjectsAlt] = alt;
    data[jsonKeyMovieListSubjectsId] = id;
    return data;
  }
}

class MovieList {
/*
 {
  "count": 13,
  "start": 1,
  "total": 28,
  "subjects": [
    {
      "rating": {
        "max": 10,
        "average": 8.6,
        "details": {
          "1": 384,
          "2": 1292,
          "3": 10092,
          "4": 30482,
          "5": 35759
        },
        "stars": "45",
        "min": 0
      },
      "genres": [
        "剧情"
      ],
      "title": "哪吒之魔童降世",
      "casts": [
        {
          "avatars": {
            "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
            "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp",
            "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1564150860.79.webp"
          },
          "name_en": "Yanting Lü",
          "name": "吕艳婷",
          "alt": "https://movie.douban.com/celebrity/1419996/",
          "id": "1419996"
        }
      ],
      "durations": [
        "110分钟"
      ],
      "collect_count": 757191,
      "mainland_pubdate": "2019-07-26",
      "has_video": false,
      "original_title": "哪吒之魔童降世",
      "subtype": "movie",
      "directors": [
        {
          "avatars": {
            "small": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
            "large": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp",
            "medium": "https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1547719747.9.webp"
          },
          "name_en": "Yu Yang",
          "name": "饺子",
          "alt": "https://movie.douban.com/celebrity/1328441/",
          "id": "1328441"
        }
      ],
      "pubdates": [
        "2019-07-13(大规模点映)"
      ],
      "year": "2019",
      "images": {
        "small": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
        "large": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp",
        "medium": "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2563780504.webp"
      },
      "alt": "https://movie.douban.com/subject/26794435/",
      "id": "26794435"
    }
  ],
  "title": "正在上映的电影-南京"
} 
*/

  int count;
  int start;
  int total;
  List<MovieListSubjects> subjects;
  String title;

  MovieList({
    this.count,
    this.start,
    this.total,
    this.subjects,
    this.title,
  });
  MovieList.fromJson(Map<String, dynamic> json) {
    count = json[jsonKeyMovieListCount];
    start = json[jsonKeyMovieListStart];
    total = json[jsonKeyMovieListTotal];
  if (json[jsonKeyMovieListSubjects] != null) {
  var v = json[jsonKeyMovieListSubjects];
  var arr0 = List<MovieListSubjects>();
  v.forEach((v) {
  arr0.add(MovieListSubjects.fromJson(v));
  });
    subjects = arr0;
    }
    title = json[jsonKeyMovieListTitle];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data[jsonKeyMovieListCount] = count;
    data[jsonKeyMovieListStart] = start;
    data[jsonKeyMovieListTotal] = total;
    if (subjects != null) {
      var v = subjects;
      var arr0 = List();
  v.forEach((v) {
  arr0.add(v.toJson());
  });
      data[jsonKeyMovieListSubjects] = arr0;
    }
    data[jsonKeyMovieListTitle] = title;
    return data;
  }
}
